# Generated by Django 3.1.4 on 2020-12-14 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepostblog',
            name='descricao',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='samplepostblog',
            name='title',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.CreateModel(
            name='DestaquePostBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('descricao', models.TextField(verbose_name='')),
                ('imagem', models.TextField(verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
